### ISSUE TITLE
disable addition of new "Research Data" publications in old biblio when new biblio is in pilot phase

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#219] opened 2021-12-09 16:21 UTC
**Describe the improvement**
I think we already discussed this, but to make sure it is not forgotten.

Ass the metadata of the publications of type "Research Data" is different from the metadata of datasets in the new biblio, we would like to disable the addition of new publications of type "Research Data" (e.g. by removing this type from the drop down?). Researchers that urgently need to submit data will be pointed to the new biblio by the data stewards, but we do not expect this will occur often.

**Comment by nics** [comment] 2021-12-09 16:23
duplicate of #106

**Closed by nics** 2021-12-09 16:23 UTC
Labels: enhancement
