### ISSUE TITLE
some radio buttons of publication import methods cannot be selected

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#398] opened 2022-06-03 12:44 UTC
**Describe the improvement**
In the first step of the publication workflow, a method to add a publication needs to be chosen by cliciking 1 of 4 methods. This can be done by clicking the box in all cases. In the top two options this can also be done by clicking the radio button (the circle) itself. However, in the lower two options, clicking the radio button results in the selection of the above option.

e.g. when the radio button of "Import via Bibtex file." is clicked, "Import your publication via an identifier." is selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/171855737-ac55581c-94fc-497c-a0bf-688557e128e0.png)

**Comment by mietcls** [comment] 2022-08-23 14:43
@sdebodt I was not able to reproduce this bug (Firefox, Chrome, Safari) – do you still have the issue? If not, we can close this one :-)

**Comment by sdebodt** [comment] 2022-08-24 07:44
I still have the issue. It occurs for the 2 lower options (Enter a publication manually and Import via Bibtex file). Clicking the text box is fine, clicking the radio button itself results in the selection of the method above the one that was clicked.

Chrome Versie 104.0.5112.101 (Officiële build) (64-bits)

**Comment by mietcls** [comment] 2022-08-24 08:01
Tested on https://eliot1.ugent.be/biblio-backend/publication with @sdebodt – bug has been fixed on this environment.

**Closed by mietcls** 2022-08-24 08:01 UTC
Labels: bug
