### ISSUE TITLE
embargo for datasets

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#217] opened 2021-12-09 16:01 UTC
**Describe the improvement**
Can embargo date, date type (of the embargo date) and access level after embargo by added for datasets, as is done for publications? 

This info is most probably not available in the DataCite metadata and will have to be added manually by the submitter.

This is needed to decide on which datasets to provide to FRIS at a certain point in time.

**Comment by nics** [comment] 2021-12-09 18:58
is this required by fris or just recommended? we'll ad it to the next milestone if not required

**Comment by sdebodt** [comment] 2021-12-10 09:00
it is required by FRIS.

**Comment by nics** [comment] 2021-12-11 13:51
Added the fields in 3478ad506ba08e35e0b73e710b8992c40045e8ce.
@sdebodt can you tell me what the semantics should be? e.g. an after embargo access level can only be chosen if access level is embargoed, ...

**Comment by sdebodt** [comment] 2021-12-13 14:07
If conditional is possible, then only show fields "Embargo period" and "Access level after embargo period" when "Access level" = Embargoed access.

Access level after embargo can be "Open access" and "Restricted access".

**Comment by netsensei** [comment] 2021-12-14 11:21
Implemented a conditional.

* Default state: "Period" and "Access level" are disabled and empty if the field value isn't "Embargo access".
* Selecting "Embargo access" unlocks the fields and allows the user to input values (date, access level).
* Selecting any other value (e.g. open access) will disable the fields again.

At no point are any selected values in the fields "Embargo access" or "Period" cleared or removed if any other values ("open access", "restricted access", "closed access") are selected. This caters to the principle of "least surprise": the idea to not surprise users with unexpected behavior.

However, this means that a record can be set to e.g. "restricted access" while the fields "Period" / "Access level" are still set to the values which only carry meaning in an "embargo access" context. If this seems to too confusing, I can change the logic to automatically reset those fields if "embargo access" is changed to another value.

**Comment by netsensei** [comment] 2021-12-14 12:22
Closing this for now.

**Closed by netsensei** 2021-12-14 12:22 UTC
Labels: enhancement

**Comment by sdebodt** [comment] 2021-12-15 12:01
Embargo period and future access level are grey but can be edited independent of the access level that is chosen.

**Comment by netsensei** [comment] 2021-12-15 14:39
I see the same issue. Apparently, I was trying to fight with how browsers process / submit form elements which are set to "disabled".  I've fixed this and changed the behavior somewhat since the clearing the "Period" and "Access level" fields manually when "Embargo access" is selected was unwieldy.

* Default state: "Period" and "Access level" are disabled and empty if the field value isn't "Embargo access".
* Selecting "Embargo access" unlocks the fields and allows the user to input values (date, access level).
* Selecting any other value (e.g. open access) will disable the fields again.
* **The values of  the "Period" and "Access level" fields are cleared.**

**Comment by sdebodt** [comment] 2021-12-15 14:47
perfect!
