### ISSUE TITLE
reactivate full reindex cron job

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#849] opened 2022-11-23 13:03 UTC

**Comment by nicolasfranck** [comment] 2022-11-23 13:52
important: never, never throw away records from the index. fix bump_date_updated uses old record to bump date updated. This is because additional enrichment is done during indexation.

**Comment by nicolasfranck** [comment] 2022-12-06 14:37
starts fast (150r/s), and then gradually becomes slower, ending at 18r/s around 100K (and then ending stable)

**Comment by nicolasfranck** [comment] 2022-12-06 15:21
@nics the fix `set_list_item_status` also has a severe impact (an update and commit pér record). You're trying to synchronize the status of a record in the lists and the status of the publication in the index, right? Are these lists long? Maybe expand these lists on demand, and filter them by their status like that?

**Comment by nicolasfranck** [comment] 2022-12-06 19:19
@nics apparently yes, biggest are around 600 records

**Comment by nics** [comment] 2022-12-07 08:09
@nicolasfranck sure lots of improvement possible there, can you propose something?

**Comment by nicolasfranck** [comment] 2022-12-07 08:25
@nics Did a retest with that fix, but apparently didn't have the impact I thought it had. I'm chasing a ghost here ;-)

**Comment by nicolasfranck** [comment] 2022-12-08 07:36
And test with `catmandu reindex_publications --index-all -v`:

```
[..]
added    339000 (16/sec)
added    339100 (16/sec)
added    339200 (16/sec)
added    339300 (16/sec)
added    339400 (16/sec)
added    339500 (16/sec)
added    339600 (16/sec)
Oops! index_at_alias

real    350m59.569s
user    34m0.203s
sys     2m16.229s
```

That last statement was probably caused by a competing cronjob (indexation based on timestamp) that recreated the index at that location. Maybe I should make sure the alias exists BEFORE starting indexation..

**Comment by nicolasfranck** [comment] 2022-12-10 15:23
@nics in the job "index_publications" there is "purge" step. This is to deal with publication list in the frontend that contain links to records that are fully removed (so not just set to "deleted", but deleted from the table). Is this still valid? I mean, yeah, we can still remove records from that table, but the software itself will never purge anything, not?

Or I could just flip the coin, and test the validity the other way around, by fetching all publication identifiers from the list_item and check them in the backend, as list_item will always be smaller.

**Comment by nicolasfranck** [comment] 2022-12-10 15:27
Besides: if the purge step is important, we should probably split this one out, because it is not ment to influence the index. And the command reindex_publications does not use it at all.

**Comment by nics** [comment] 2022-12-10 16:58
@nicolasfranck the grpc client has a purge command

**Comment by nicolasfranck** [comment] 2022-12-11 12:58
> @nicolasfranck sure lots of improvement possible there, can you propose something?

not really. The only scalable solution I can think of is to put these lists in the same database as biblio-backoffice and let postgres do the foreign key management (`on update do ..`), which will work probably more accurate and faster. But yeah, that is mixing backend and frontend (if that matters).

And then there is still the question of purging of records

**Comment by nicolasfranck** [comment] 2022-12-12 10:15
btw what is the purpose of that `reindex_publications` now?

**Comment by nics** [comment] 2022-12-12 10:17
needs to be rewritten as an index switcher

**Comment by nicolasfranck** [comment] 2022-12-13 19:25
note: when using incremental indexing, unable to use latest "date_updated" as we are mixing publications and datasets in the same destination index. e.g. latest datasets are much younger, and they are indexed first. If indexation in the middle, and you run the command again, it will pick up the latest "date_updated", which lies in 2022-12 because there are recents datasets, but the latest regular publication is much older.

**Comment by nicolasfranck** [comment] 2022-12-19 09:38
@nics feel free to reenable the cronjob [here](https://github.ugent.be/Universiteitsbibliotheek/biblio/blob/master/cron.d/biblio#L25) if you feel sure about it

**Comment by mietcls** [comment] 2023-04-17 09:41
@nicolasfranck what's the status on this one?

**Comment by nicolasfranck** [comment] 2023-04-17 09:45
@mietcls this does not run anymore automatically as it takes too long to complete.
Is only run manually when fields are added/changed, but in normal cases an incremental
update of the index is better suitable. Right @nics ?

**Comment by mietcls** [comment] 2023-04-17 12:31
If it's not relevant anymore, you can always adapt this one or close it and add an other issue linking to this one 🙏

**Closed as completed** 2023-04-17 12:42 UTC
