### ISSUE TITLE
I can proceed to the next step with a dataset that is not available in DataCite 

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#218] opened 2021-12-09 16:09 UTC
**Describe the improvement**
10.1594/PANGAEA.937928

This dataset is not available in DataCite. It is a dataset that is under review with the repository. When I entered this DOI in the past, I got an error. Now, I can proceed to the next step without error. The form is completely empty as no metadata could be retrieved. 

Related to https://github.com/ugent-library/biblio-backend/issues/206 and https://github.com/ugent-library/biblio-backend/issues/190
redundant with https://github.com/ugent-library/biblio-backend/issues/210, I assume

**Comment by nics** [comment] 2021-12-09 16:24
duplicate of #210

**Closed by nics** 2021-12-09 16:24 UTC
Labels: bug
