### ISSUE TITLE
Bug: deletion of keyword - other edits in same form are linked and random closing

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#414] opened 2022-06-20 14:57 UTC
**Describe the improvement**
When editing the dataset details, something goes wrong when removing keywords and subsequently changing e.g. the access level. In some cases, after deleting the keywords and subsequently changing the access level (without clicking save in between), the deleted keywords reappear or an existing keyword is re-added multiple times. 

A similar behavior for adding/deleting data formats.

example: 10.1594/pangaea.822313

screenshot:
![image](https://user-images.githubusercontent.com/72742841/174629588-6e533242-b423-4650-b890-c1026b600712.png)

# Technical info

- OS: MacOS Monterey 12.5.1
- Browser:
  - Safari version 15.6.1 (17613.3.9.1.16)
  - Firefox version 104.0 (64-bit)
  - Chrome version 104.0.5112.101

**Comment by mietcls** [comment] 2022-06-22 09:01
@sdebodt Which browser was this (and which version), so we can reproduce the bug?

**Comment by sdebodt** [comment] 2022-06-22 09:22
in my case Chrome.

It occurs when you delete multiple keywords. If you delete only the last keyword,  everything is fine.

**Comment by nicolasfranck** [comment] 2022-08-30 12:04
weird. I cannot reproduce this on my local development server. @nics what version is deployed on backend.bibliotest.ugent.be?

**Comment by sdebodt** [comment] 2022-08-30 12:38
I just checked with Kevin as he reported this issue. He tested it on eliot1 and also has the issue there.

**Comment by sdebodt** [comment] 2022-08-30 12:48
on eliot1, the edit form closes when selecting the access level (after deleting some keywords).

**Comment by mietcls** [comment] 2022-08-30 13:07
@sdebodt Can we have the OS, the browser + version, screenshots and steps to reproduce for each issue (keywords, closing after acces level, ...)?

**Comment by sdebodt** [comment] 2022-08-31 07:03
windows 10
chrome Versie 104.0.5112.102

Steps:

- Take a DOI for a dataset with many keywords (e.g., 10.1594/pangaea.822313). 
- Upload it as a new entry. 
- Click "Edit" to edit the the Dataset Details. 
- Delete any number of the keywords using the "garbage can" icon. 
- Then, without saving those edits, change the access level using the associated dropdown menu. 
-  in biblio test: the deleted keywords will return, and may even appear in a new order (at least in https://backend.bibliotest.ugent.be/).
- in eliot1: the edit form closes

**Comment by sdebodt** [comment] 2022-08-31 07:07
![image](https://user-images.githubusercontent.com/72742841/187614773-0191088d-97bc-4830-b7f5-7641d64fcb81.png)

![image](https://user-images.githubusercontent.com/72742841/187614874-b0f105ca-db36-4a40-ac6f-783f1a017ccb.png)

![image](https://user-images.githubusercontent.com/72742841/187614947-3f97f86d-57b2-44cd-92f1-cad92f6003ec.png)

![image](https://user-images.githubusercontent.com/72742841/187615035-46419d7a-ae99-427a-a3f3-6a4451ce7711.png)

![image](https://user-images.githubusercontent.com/72742841/187615093-84d83bf1-e75b-4bf6-a826-7688333b3ef9.png)

it can take a few seconds after selecting the access level to open access before the form disappears.

**Comment by mietcls** [comment] 2022-08-31 09:52
@sdebodt clear! I was able to reproduce the closing issue ONCE – interesting that it only happens with a *new* creation and only whenever we've touched the keywords.

Unfortunately I forgot to turn on my console log and haven't been able to reproduce it again. Highly annoying ghost bug.

**Comment by sdebodt** [comment] 2022-08-31 11:13
I still have the issue in eliot1. Have you tried private browsing?

**Comment by mietcls** [comment] 2022-08-31 11:44
Yes, no result. If you have a screenshot of any errors in the console log, we can get closer.

Right click, inspect element, go to console:
<img width="949" alt="Schermafbeelding 2022-08-31 om 13 43 11" src="https://user-images.githubusercontent.com/1572885/187670885-afdf1031-c59b-449c-afe2-464610d9c153.png">
<img width="564" alt="Schermafbeelding 2022-08-31 om 13 43 19" src="https://user-images.githubusercontent.com/1572885/187670904-92b209fb-ac1f-4984-814d-d7e0a054c8fb.png">
<img width="570" alt="Schermafbeelding 2022-08-31 om 13 43 24" src="https://user-images.githubusercontent.com/1572885/187670926-81101d46-644d-49ef-8e73-5df42ac48350.png">

**Comment by mietcls** [comment] 2022-08-31 11:49
Error did not happen, but this console log was caught in Firefox:
<img width="479" alt="Schermafbeelding 2022-08-31 om 13 49 07" src="https://user-images.githubusercontent.com/1572885/187671770-2756ee39-8d03-4211-9466-6984d346a896.png">

**Comment by sdebodt** [comment] 2022-08-31 12:00
I do not see anything in the console (not in Chrome and not in Firefox). Which element should I inspect?

**Comment by mietcls** [comment] 2022-08-31 12:04
That's okay, not one specific element – it was just the way to get there. It logs it for the entire app.

I just needed to know whether the console logged any errors while clicking around and the error happens. Thank you.

**Comment by mietcls** [comment] 2022-09-02 07:28
Note:
- doubling has been solved
- the accidental closing of the modal has not been solved after clicking on the dropdown

**Comment by nicolasfranck** [comment] 2022-09-05 07:49
Note: I see this in the logs, when selecting an access level:

```
{"level":"info","ts":1662364034.134825,"caller":"logging/logging.go:22","msg":"PUT /dataset/01GC69FX8B3XPKF1AKTSH0FH7T/details/edit/access-level (code=200 dt=123.818458ms written=12991)"}
```

**Comment by nicolasfranck** [comment] 2022-09-05 08:23
@mietcls issue about access level has been moved to https://github.com/ugent-library/biblio-backend/issues/538

**Comment by mietcls** [comment] 2022-09-05 08:30
@nicolasfranck if this one is superfluous by the existence of the new issue, you can close it as we still have the reference.

**Comment by mietcls** [comment] 2022-09-05 09:27
@nicolasfranck Sorry reopening, I now realise the issue you mentioned is part of https://github.com/ugent-library/biblio-backend/issues/440 which I will be rewriting –which is not (or just a fraction is) connected to this random closing if I understand correctly.

**Comment by mietcls** [comment] 2022-09-21 08:57
@nicolasfranck was this one fixed now?

**Closed** 2022-09-22 14:30 UTC
Labels: bug, datasets
