### ISSUE TITLE
Ask user to explicitly select an access level

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#74] opened 2021-11-08 14:12 UTC
**Describe the improvement**
Upon upload of a publication file in the "add single publication" workflow, a user will upload a publication file after which this file is displayed with the access level "Open access". This access level is chosen by default, the user cannot choose the access level before upload or during upload. An improvement could be that the access level as set to "undefined" by default, such that the user has to explicitly select the appropriate access level. Note that the access level cannot be changed when moving forward to the "Complete description" step (i.e. you cannot go back to the "Import file" step from the "complete description" step).

**To Reproduce**
If something does not work as expected, which steps did you take?
1. Go to 'Import file step' (https://eliot1.ugent.be/biblio-backend/publication/add-single/import) of "Add single publication' workflow
2. Upload publication file
3. Scroll down to see access level of file.
4. Access level is set to "Open access"

**Expected behavior**
Set access level to undefined after upload of publication file. Mandatory selection of appropriate access level by user before being able to got to "Complete description" step.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/140756807-bb5450ed-538b-4ee7-a8e1-cb503f5432a2.png)

**Additional context**
https://onderzoektips.ugent.be/en/tips/00001670/

**Comment by nics** [comment] 2021-11-18 15:12
duplicate of #102

**Comment by sdebodt** [comment] 2021-11-30 09:53
As suggested by @nicolasfranck yesterday, can we explore whether a popup after the file upload is feasible to inform the user that an appropriate access level needs to be selected and that the 3 dots can be used to change the properties of the uploaded file.

**Comment by nics** [comment] 2021-12-07 12:23
since 5f4877a5c4cbb9fc47377ad3dc5c16777c8df111 the file edit dialog is opened after file upload

**Closed by nics** 2021-12-07 12:23 UTC
Labels: enhancement
